server:
  port: 8001
# ActuatorWeb访问端口
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always


spring:
  application:
    name: toast-user-service

  cloud:
    nacos:
      discovery:
        server-addr:  #配置Nacos地址

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包 com.mysql.jdbc.Driver org.gjt.mm.mysql.Driver
    url: 
    username: root
    password: 689692630

  redis:
    host: 
    lettuce:
      shutdown-timeout: 0ms
      pool:
        MaxTotal: 20 #最大连接数
        minIdle: 1
        maxWaitMillis: 5000
        maxIdle: 5
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true

  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
file:
  ###静态资源对外暴露的访问路径
  staticAccessPath: /api/file/**
  ###静态资源实际存储路径  如果没有结尾的 / 就404
  uploadFolder: 

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.toast.work.domain   # 所有Entity别名类所在包

wxLogin:
  yiDengSecret: b7ecbb58
